

model_name: meta-llama/Llama-3.1-8B-Instruct
sentence_transformer_model: BAAI/bge-m3
experiment_name: hard-prompting-baseline-8b


context:
  context_type: null # Choices: "text" or "graph". Use null if no context is needed.
  top_k: 0 # How many instances to retrieve
  hops: 0 # Also include hops in the knowledge graph from retrieved instances
