model_name: meta-llama/Llama-3.2-3B-Instruct
sentence_transformer_model: BAAI/bge-m3
experiment_name: few-shot-retrieval-3b
checkpoint_path: models
graph_path: gnd/gnd.pickle
dataset_path: dataset

context:
  context_type: text # Choices: "text" or "graph". Use null if no context is needed.
  top_k: 5 # How many instances to retrieve
  hops: 0 # Also include hops in the knowledge graph from retrieved instances
  title_wise: false # Whether to retrieve title-to-label or title-to-title
  relation: null # Choices: null (use all relations) "broader" or "related"
  index_path: "data/label_index.pkl"
  mapping_path: "data/label_mapping.pkl"
