model_name: meta-llama/Llama-3.1-8B-Instruct
sentence_transformer_model: KatjaK/gnd_retriever_full
experiment_name: few-shot-ft-3k-1hop-label-retrieval-8b

context:
  context_type: text # Choices: "text" or "graph". Use null if no context is needed.
  top_k: 3 # How many instances to retrieve
  hops: 1 # Also include hops in the knowledge graph from retrieved instances
  best_example: True