model_name: meta-llama/Llama-3.2-3B-Instruct
sentence_transformer_model: KatjaK/gnd_retriever_full
experiment_name: few-shot-ft-1k-label-retrieval-with-best-ex-3b

context:
  context_type: text # Choices: "text" or "graph". Use null if no context is needed.
  top_k: 1 # How many instances to retrieve
  hops: 0 # Also include hops in the knowledge graph from retrieved instances
  best_example: True